language: objective-c
osx_image: xcode7.2
cache: cocoapods
podfile: Podfile
before_install:
- pod install
script:
- |
  set -o pipefail && \
  xcodebuild test \
  -workspace HNAPI.xcworkspace \
  -scheme HNAPI_Tests \
  -sdk iphonesimulator \
  -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' \
  ONLY_ACTIVE_ARCH=NO \
  | xcpretty
