language: objective-c
osx_image: xcode7.2
script:
- |
  set -o pipefail && \
  xcodebuild test \
  -project HNAPI.xcodeproj \
  -scheme HNAPI_Tests \
  -sdk iphonesimulator \
  -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' \
  ONLY_ACTIVE_ARCH=NO \
  | xcpretty
