source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HNAPI_Tests' do
  pod 'HNAPI', :path => '../'
  pod 'Quick'
  pod 'Nimble'
  pod 'Moya', '~> 6.0'
  pod 'Moya-ObjectMapper', '~> 1.1'
  pod 'Moya-ObjectMapper/RxSwift', '~> 1.1'
end
